
- name: install mysql
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - mysql-server
    - python-mysqldb

- name: create snipeit database
  mysql_db:
    name: snipeit
    state: present

- name: create snipeit_user
  mysql_user:
    name: "snipeit_user"
    password: "{{ snipeit_password }}"
    host: '%'
    priv: 'snipeit.*:ALL'
    state: present

- name: unbind mysql from localhost
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: '#bind-address = 127.0.0.1'
    backrefs: yes
  register: mysql_config

- name: restart and enable mysql
  service:
    name: mysql
    state: restarted
    enabled: yes
  when: mysql_config is changed

