
- name: install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - python
    - python-mysqldb
    - git
    - composer
    - unzip
    - php7.2-mbstring
    - php7.2-xml
    - php7.2-dev
    - libmcrypt-dev
    - php7.2-gd
    - php7.2-zip
    - php7.2-curl
    - php7.2-bcmath
    - php7.2-mysql
    - php7.2-ldap
    - apache2
    - libapache2-mod-php7.2

- name: remove default index.html
  file:
    path: /var/www/html/index.html
    state: absent

- name: clone snipeit
  git:
    repo: https://github.com/snipe/snipe-it
    dest: /var/www/html
    version: master
    force: yes


- name: set permissions for /var/www/html
  file:
    dest: "/var/www/html"
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
    follow: no

- name: add the .env config
  template:
    src: source/.env
    dest: /var/www/html/.env
    owner: www-data
    group: www-data
    mode: 0700

- name: run composer
  shell: | 
      #!/bin/bash
      
      cd /var/www/html
      composer install --no-dev --prefer-source
  register: command_result
  changed_when: "'Nothing to install or update' not in command_result.stderr"

- name: run artisan
  shell: |
      #!/bin/bash

      cd /var/www/html
      php artisan migrate --force
  register: command_result
  changed_when: "'Nothing to migrate.' not in command_result.stdout"

- name: generate artisan keys
  shell: |
      #!/bin/bash
      
      cd /var/www/html
      php artisan key:generate --force

- name: change vhost's document root to /var/www/html/public
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    regexp: 'DocumentRoot'
    line: '        DocumentRoot /var/www/html/public'
    #    backrefs: yes
  register: vhost

- name: add apache config to allow overwrites
  template:
    src: source/apache2.conf
    dest: /etc/apache2/apache2.conf
  register: apache_config

- name: enable default site
  command: a2ensite 000-default.conf
  changed_when: "'Site 000-default already enabled' not in site_enable.stdout"
  register: site_enable

- name: enable mod_rewrite
  command: a2enmod rewrite
  changed_when: "'Module rewrite already enabled' not in mod_rewrite_enable.stdout"
  register: mod_rewrite_enable

- name: restart and enable
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: vhost is changed or apache_config is changed or site_enable is changed or mod_rewrite_enable is changed


