
- name: install dependencies
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git 
    - g++ 
    - imagemagick 
    - xclip 
    - libsdl1.2-dev 
    - libglu1-mesa-dev 
    - libgl1-mesa-dev

